cluster: "submit.py"
cluster-status: "status.py"
jobscript: "jobscript.sh"
jobs: 8
restart-times: 0
immediate-submit: false
verbose: false
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
rerun-incomplete: true  # recomended for cluster submissions
keep-going: false
default-resources: ["mem_mb=64000"]
use-singularity: true
use-conda: true
resources: gpu=1
cores: 8
cache: false
reason: true
# if CPU nodes don't have access to cuda dirs, use
# export CUDA_DIR=$(CUDA_DIR); $(SNAKEMAKE) ...
# singularity-args: "--bind $(SHARED_ROOT),/tmp --nv --containall"
singularity-args: "--bind /projappl/project_2007095/tommi/data,$CUDA_INSTALL_ROOT,$CUDNN_INSTALL_ROOT:/cudnn,/projappl/project_2007095/tommi/data/temp:/tmp --nv --containall"
config:
  - deps=false
  - root=/projappl/project_2007095/tommi/data
  - cuda=/appl/spack/v017/install-tree/gcc-11.2.0/cuda-11.5.0-mg4ztb/
  - cudnn=/appl/spack/v017/install-tree/gcc-11.2.0/cudnn-8.3.3.40-11.5-crjjbv/
  - workspace=10000
  - numgpus=1
  - mariancmake=""
  - gpus="0"
