---
trust-domain: "translations"
task-priority: low
task-deadline-after: 60 days
task-expires-after: 90 days
treeherder:
    group-names:
        "I": "Docker images"
        "Fetch": "Fetching tasks"

taskgraph:
    register: translations_taskgraph:register
    decision-parameters: "translations_taskgraph.parameters:get_decision_parameters"
    repositories:
        firefox_translations_training:
            name: "firefox-translations-training"

# The list of valid stages that can be used with `target-stage and `start-stage`.
# These get attached to tasks in `kinds`.
valid-stages:
    - clean-corpus
    - clean-mono
    - bicleaner
    - bicleaner-model
    - merge-corpus
    - merge-devset
    - merge-mono
    - train-vocab
    - train-backwards
    - evaluate-backwards
    - split-corpus
    - split-mono
    - translate-mono-trg
    - collect-mono-trg
    - train-teacher
    - evaluate-teacher
    - evaluate-finetuned-teacher
    - translate-corpus
    - extract-best
    - collect-corpus
    - translate-mono-src
    - collect-mono-src
    - merge-translated
    - score
    - cefilter
    - alignments
    - train-student
    - evaluate-student
    - finetune-student
    - evaluate-finetuned-student
    - quantize
    - evaluate-quantized
    - export
    - evaluate-teacher-ensemble
    - analyze-mono
    - all

workers:
    aliases:
        # Use for quick tasks that don't require GPUs, eg: linting, tests
        b-cpu:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-large-gcp'
        # Use for tasks that don't require GPUs, but need lots of disk space
        # eg: dataset cleaning & merging
        b-cpu-largedisk:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-large-gcp-300gb'
        # Use for tasks that don't require GPUs, but need immense amounts of disk space
        # eg: alignments
        b-cpu-xlargedisk:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-large-gcp-1tb'
        # Use for tasks that don't require GPUs, but need immense amounts of disk space
        # and higher reliability
        b-cpu-xlargedisk-standard:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-large-gcp-1tb-standard'
        # Use for quick tasks that need a GPU, eg: evaluate
        b-gpu:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: 'b-linux-v100-gpu'
        # Use for tasks that need lots of GPU power, but not lots of disk space
        # eg: translation & scoring
        b-largegpu:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: 'b-linux-v100-gpu-4'
        # Use for tasks that needs lots of GPU power and increased disk space
        # eg: bicleaner
        b-largegpu-largedisk:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: 'b-linux-v100-gpu-4-300gb'
        # Use for tasks that need lots of GPU power and immensive amounts of disk space
        # eg: training
        b-largegpu-xlargedisk:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: 'b-linux-v100-gpu-4-1tb'
        # Use for tasks that needs lots of GPU power, increased disk space, and higher reliability
        b-largegpu-largedisk-standard:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: 'b-linux-v100-gpu-4-300gb-standard'
        # Use for tasks that needs lots of GPU power, increased disk space, and higher reliability
        b-largegpu-xlargedisk-standard:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: 'b-linux-v100-gpu-4-1tb-standard'
        images:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'

# Keys are worker type, and align with the `worker-type` entries in the
# `worker.aliases` above.
worker-configuration:
    b-linux-v100-gpu:
        env:
            GPUS: "0"
            WORKSPACE: "12000"

    b-linux-v100-gpu-4:
        env:
            GPUS: "0 1 2 3"
            WORKSPACE: "12000"

    b-linux-v100-gpu-4-300gb:
        env:
            GPUS: "0 1 2 3"
            WORKSPACE: "12000"

    b-linux-v100-gpu-4-1tb:
        env:
            GPUS: "0 1 2 3"
            WORKSPACE: "12000"

    b-linux-v100-gpu-4-300gb-standard:
        env:
            GPUS: "0 1 2 3"
            WORKSPACE: "12000"

    b-linux-v100-gpu-4-1tb-standard:
        env:
            GPUS: "0 1 2 3"
            WORKSPACE: "12000"
