---
trust-domain: "translations"
task-priority: low
task-deadline-after: 5 days
treeherder:
    group-names:
        "I": "Docker images"
        "Fetch": "Fetching tasks"

taskgraph:
    register: translations_taskgraph:register
    decision-parameters: "translations_taskgraph.parameters:get_decision_parameters"
    repositories:
        firefox_translations_training:
            name: "firefox-translations-training"

workers:
    aliases:
        b-linux-large:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
        b-linux-large-300gb:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux-large-gcp-300gb'
        b-linux-v100-gpu:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: '{alias}'
        b-linux-v100-gpu-4:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: '{alias}'
        b-linux-v100-gpu-4-300gb:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: '{alias}'
        b-linux-v100-gpu-4-1tb:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: '{alias}'
        images:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
