---
trust-domain: "translations"
task-priority: low
treeherder:
    group-names:
        "I": "Docker images"
        "Fetch": "Fetching tasks"
        "TL": "Toolchain tasks"
        "flores": "flores"
        "sacrebleu": "sacrebleu"
        "opus": "opus"
        "mtdata": "mtdata"
        "news-crawl": "news-crawl"

taskgraph:
    register: translations_taskgraph:register
    decision-parameters: "translations_taskgraph.parameters:get_decision_parameters"
    repositories:
        firefox_translations_training:
            name: "firefox-translations-training"

# It's not exactly _ideal_ to have all of the locale pairs for each dataset
# specified in this file, but it's very difficult (if not impossible) to
# generate the right `dataset` tasks without it. We _could_ attempt to pull
# the locale pair for all datasets listed here, but not all locales or pairs
# exist for each dataset...which means we'll end up with failures that block
# the rest of the graph.
# There may be other ways to make this work, but in the short term this is
# the most straightforward solution.
datasets:
    flores:
        dev:
            - src: en
              trg: ru
            - src: en
              trg: fr
            - src: ru
              trg: en
        devtest:
            - src: en
              trg: ru
            - src: en
              trg: fr
            - src: ru
              trg: en

    sacrebleu:
        wmt19:
            - src: en
              trg: ru
            - src: ru
              trg: en
        wmt20:
            - src: en
              trg: ru
            - src: ru
              trg: en

    opus:
        ada83/v1:
            - src: en
              trg: ru
            - src: ru
              trg: en
        GNOME/v1:
            - src: en
              trg: ru
            - src: ru
              trg: en

    news-crawl:
        news.2020:
            - src: en
              trg: ru
            - src: ru
              trg: en

    mtdata:
        Neulab-tedtalks_train-1-eng-rus:
            - src: en
              trg: ru
            - src: ru
              trg: en

workers:
    aliases:
        b-linux:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
        b-linux-large:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
        # TODO: this should probably be b-linux...need to update ci-config
        t-linux-v100-gpu:
            provisioner: '{trust-domain}-{level}'
            implementation: generic-worker
            os: linux
            worker-type: '{alias}'
        images:
            provisioner: '{trust-domain}-{level}'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
        t-linux-large:
            provisioner: '{trust-domain}-t'
            implementation: docker-worker
            os: linux
            worker-type: '{alias}-gcp'
