cluster: "submit.py"
cluster-status: "status.py"
jobscript: "jobscript.sh"
jobs: 1
restart-times: 0
immediate-submit: false
verbose: false
max-jobs-per-second: 1
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
rerun-incomplete: true  # recomended for cluster submissions
keep-going: false
default-resources: "mem_mb=64000"
use-singularity: true
use-conda: true
resources: gpu=1
cores: 8
#cache: false
reason: true

singularity-args: "--bind /pfs/lustrep1/scratch/project_462000088/members/niemine1/data,/pfs/lustrep1/scratch/project_462000088/members/niemine1/data/tmp:/tmp --rocm --containall"
config:
  - deps=false
  - root=/pfs/lustrep1/scratch/project_462000088/members/niemine1/data
  - rocm=/opt/rocm
  - workspace=20000
  - numgpus=1
  - mariancmake=""
  - gpus=""
  - marianversion="lumi-marian"
