## https://github.com/marian-nmt/marian-examples/tree/master/wmt2017-uedin
beam-size: 12
cost-type: ce-mean-words
disp-freq: 1000
early-stopping: 5
exponential-smoothing: true
max-length: 100
maxi-batch: 1000
mini-batch-fit: true
normalize: 1
save-freq: 10000
valid-freq: 10000
valid-mini-batch: 64
