# https://discourse.translatelocally.com/t/marian-configuration-to-use/24
dim-vocabs: [32000, 32000]
type: transformer
# tasks: https://github.com/marian-nmt/marian-dev/blob/master/src/common/aliases.cpp
task: transformer-big
# task: transformer-base  # use smaller model for low resource (<5M sentences)
