####
# Test config, it rus the pipeline quickly end to end
###


root: ""
cuda: ""
deps: false
gpus: ""
numgpus: ""
workspace: ""
mariancmake: ""

experiment:
  name: test
  src: ru
  trg: en

  teacher-ensemble: 2
  backward-model: ""
  vocab: ""

  mono-max-sentences-src: 100000
  mono-max-sentences-trg: 200000
  split-length: 100000
  spm-sample-size: 100000

  best-model: chrf

  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      opus_ada83/v1: 0
      mtdata_Neulab-tedtalks_train-1-eng-rus: 0.6

marian-args:
  training-backward:
    after: 1000u
  training-teacher-base:
    after: 1000u
  training-teacher-finetuned:
    after: 2000u
  training-student:
    after: 1000u
  training-student-finetuned:
    after: 1000u
  decoding-backward:
    mini-batch-words: 2000
    precision: float16
  decoding-teacher:
    mini-batch-words: 1000
    precision: float16

datasets:
  train:
    - opus_ada83/v1
    - opus_GNOME/v1
    - mtdata_Neulab-tedtalks_train-1-eng-rus
  devtest:
    - flores_dev
    - sacrebleu_wmt19
  test:
    - flores_devtest
    - sacrebleu_wmt20
  mono-src:
    - news-crawl_news.2020
  mono-trg:
    - news-crawl_news.2020


