####
# Blazing fast run config that's also used by TaskCluster CI
###

experiment:
  name: ci
  src: ru
  trg: en

  teacher-ensemble: 1
  backward-model: ""
  vocab: ""

  mono-max-sentences-src: 10000
  mono-max-sentences-trg: 10000
  split-length: 5000
  spm-sample-size: 10000
  spm-vocab-size: 1000

  best-model: chrf

  use-opuscleaner: true
  bicleaner:
    default-threshold: 0.5
    dataset-thresholds:
      opus_ada83/v1: 0
      mtdata_ELRC-wikipedia_health-1-eng-rus: 0.6

marian-args:
  training-backward:
    disp-freq: 1
    save-freq: 5
    valid-freq: 10
    after: 10u
    dim-vocabs: "1000 1000"
  training-teacher-base:
    disp-freq: 1
    save-freq: 5
    valid-freq: 10
    after: 10u
    dim-vocabs: "1000 1000"
    task: transformer-base
  training-teacher-finetuned:
    disp-freq: 1
    save-freq: 5
    valid-freq: 10
    after: 10u
    dim-vocabs: "1000 1000"
    task: transformer-base
  training-student:
    disp-freq: 1
    save-freq: 5
    valid-freq: 10
    after: 10u
    dim-vocabs: "1000 1000"
  training-student-finetuned:
    disp-freq: 1
    save-freq: 5
    valid-freq: 10
    after: 10u
    dim-vocabs: "1000 1000"
  decoding-backward:
    mini-batch-words: 2000
  decoding-teacher:
    mini-batch-words: 1000
    precision: float16

datasets:
  train:
    - opus_ada83/v1
    - mtdata_ELRC-wikipedia_health-1-eng-rus
  devtest:
    - flores_dev
    - sacrebleu_wmt19
  test:
    - flores_devtest
    - sacrebleu_wmt20
  mono-src:
    - news-crawl_news.2008
  mono-trg:
    - news-crawl_news.2007


